### ISSUE TITLE
Option to filter out certain users

### ISSUE THREAD

**Issue by jeffreytli** [kamranahmedse/git-standup#69]
Would it be possible to include options to filter out users? We have a bunch of automated jobs as part of our deployment cycle that ends up polluting the stand-up logs.

**Comment by TheKevJames** [comment]
I have the same use-case (I've been using `git standup ... | grep -v 'renovate\[bot\]'` for _ages_). I was just about to dive into implementing this -- but it turns out this is actually already supported.

If you enable perl regexp in your git installation (`git config --global grep.patternType perl`), then you can use the existing `git-standup` author filter argument `-a` to do this:
```bash
git standup -a'^(?!(renovate\[bot\]))'
```

**Comment by kamranahmedse** [comment]
Thanks @TheKevJames I have added it to the readme 🙏
